import type { Profile } from "../entities/profile.entity";
/**
 * Input needed to create a profile.
 * excluding fields that are generated by the database.
 */
export type CreateProfileInput = Omit<Profile, "id" | "createdAt">;
export interface ProfileRepository {
  create(input: {
    authUserId: string;
    username: string;
    age: number;
    height: number;
    initialWeight: number;
  }): Promise<Profile>;
  getByUsername(username: string): Promise<Profile | null>;
  getByAuthUserId(authUserId: string): Promise<Profile | null>;
}
